instance_name: RoomMap.org
client_backend:
  port: 80
  compression: true
api_url: https://api.roommap.org:9999
resource_directory: /data/resources
freemarker_template_version: 2.3.30
website_name: Room Map