instance_name: RoomMap.org
client_backend:
  port: 80
  compression: true
api_url: http://127.0.0.1:9999
resource_directory: D:\.RoomMapResources
public_api_data_update_frequency: 300000
freemarker_template_version: 2.3.30
website_name: Room Map